import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PDFData {
    invoiceNo: string;
    invoiceTotal: number;
    auditDate: string;
    logistics: {
        road: string;
        sea: string;
        weather: string;
    };
    mathIntegrity: {
        fob: number;
        av: number;
        incentive: number;
        revenueRisk: number;
    };
    strategicFindings: string;
    caAdvice: {
        advice: string;
        type: string;
        savings: number;
    }[];
    profitProtection: {
        cashIncentive: number;
        dutyDrawback: number;
        revenueRisk: number;
        ldcRiskScore: number;
        cbamLiability: number;
    };
    lineItems: {
        format: number;
        description: string;
        qty: number;
        price: number;
        hsCode: string;
        ldcImpact: boolean;
        status: string;
    }[];
    sumCheck: {
        declared: number;
        calculated: number;
        passed: boolean;
    };
}

export const generateCFOReport = (data: PDFData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 14;

    // --- COLORS ---
    const colors = {
        navy: [30, 41, 59] as [number, number, number],
        gold: [218, 165, 32] as [number, number, number], // Darker gold for white bg
        green: [22, 163, 74] as [number, number, number],
        red: [220, 38, 38] as [number, number, number],
        blue: [37, 99, 235] as [number, number, number],
        gray: [100, 116, 139] as [number, number, number],
        lightGray: [241, 245, 249] as [number, number, number],
    };

    // --- HELPER FUNCTIONS ---
    const drawSectionHeader = (title: string, y: number, color: [number, number, number]) => {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...color);
        doc.text(title.toUpperCase(), margin, y);
        doc.setDrawColor(...color);
        doc.setLineWidth(0.5);
        doc.line(margin, y + 2, pageWidth - margin, y + 2);
        return y + 12;
    };

    const drawCard = (x: number, y: number, w: number, h: number, title: string, value: string, color: [number, number, number]) => {
        doc.setFillColor(255, 255, 255);
        doc.setDrawColor(200, 200, 200);
        doc.roundedRect(x, y, w, h, 2, 2, 'FD');

        doc.setFontSize(7);
        doc.setTextColor(...colors.gray);
        doc.text(title, x + (w / 2), y + 8, { align: 'center' }); // Centered title

        doc.setFontSize(10);
        doc.setTextColor(...color);
        doc.setFont('helvetica', 'bold');
        doc.text(value, x + (w / 2), y + 18, { align: 'center' }); // Centered value
    };

    // --- HEADER ---
    doc.setFillColor(...colors.navy);
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 215, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('CFO ACCURACY REPORT', margin, 20);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const headerRightText = `Generated by Lead-Time Guardian AI\nInvoice: ${data.invoiceNo} | Date: ${data.auditDate}`;
    const lines = doc.splitTextToSize(headerRightText, 80);
    doc.text(lines, pageWidth - margin - 80, 15, { align: 'left' });

    let currentY = 55;

    // --- 1. LOGISTICS ALERT & 2. MATH INTEGRITY (Side by Side) ---
    // Left Column: Logistics (40%)
    const leftColWidth = (pageWidth - (margin * 3)) * 0.4;
    const rightColWidth = (pageWidth - (margin * 3)) * 0.6;
    const rightColX = margin + leftColWidth + margin;

    // Section 1: Logistics
    doc.setFontSize(9);
    doc.setTextColor(...colors.blue);
    doc.setFont('helvetica', 'bold');
    doc.text('1. LOGISTICS ALERT (API DRIVEN)', margin, currentY);
    doc.setDrawColor(...colors.blue);
    doc.line(margin, currentY + 2, margin + leftColWidth, currentY + 2);

    const logBoxY = currentY + 8;
    const logBoxWidth = (leftColWidth - 4) / 3;
    const logBoxHeight = 25; // Increased height

    // Road
    drawCard(margin, logBoxY, logBoxWidth, logBoxHeight, 'ROAD', data.logistics.road, data.logistics.road.includes('Clear') ? colors.green : colors.red);
    // Sea
    drawCard(margin + logBoxWidth + 2, logBoxY, logBoxWidth, logBoxHeight, 'SEA', data.logistics.sea, data.logistics.sea.includes('Smooth') ? colors.green : colors.gold);
    // Weather
    drawCard(margin + (logBoxWidth * 2) + 4, logBoxY, logBoxWidth, logBoxHeight, 'RISK', data.logistics.weather, data.logistics.weather.includes('Safe') ? colors.green : colors.red);

    // Section 2: Math Integrity
    doc.setFontSize(9);
    doc.setTextColor(...colors.gold); // Use gold/brown for Math title
    doc.text('2. MATHEMATICAL INTEGRITY AUDIT', rightColX, currentY);
    doc.setDrawColor(...colors.gold);
    doc.line(rightColX, currentY + 2, pageWidth - margin, currentY + 2);

    const mathY = currentY + 8;

    const drawMathRow = (y: number, label: string, val: string, valColor: [number, number, number] = [0, 0, 0]) => {
        doc.setFontSize(8);
        doc.setTextColor(...colors.gray);
        doc.setFont('helvetica', 'normal');
        doc.text(label, rightColX, y);

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...valColor);
        doc.text(val, pageWidth - margin, y, { align: 'right' });

        doc.setDrawColor(240, 240, 240);
        doc.line(rightColX, y + 2, pageWidth - margin, y + 2);
    };

    drawMathRow(mathY + 4, 'FOB Value', `$${data.mathIntegrity.fob.toLocaleString()}`, colors.navy);
    drawMathRow(mathY + 12, 'AV Calculation ((FOB * 1.01) * 1.01)', `$${data.mathIntegrity.av.toLocaleString()}`, colors.navy);
    drawMathRow(mathY + 20, 'Cash Incentive (FOB * 0.08)', `$${data.mathIntegrity.incentive.toLocaleString()}`, colors.green);
    drawMathRow(mathY + 28, '2026 Revenue Risk (AV * 0.119)', `$${data.mathIntegrity.revenueRisk.toLocaleString()}`, colors.red);

    currentY += 50;

    // --- 3. STRATEGIC AUDIT FINDINGS ---
    currentY = drawSectionHeader('3. STRATEGIC AUDIT FINDINGS (AI OBSERVATION)', currentY, [236, 72, 153]); // Pinkish

    doc.setFontSize(9);
    doc.setTextColor(50, 50, 50);
    doc.setFont('helvetica', 'normal');

    // Sanitize and split text
    // Remove markdown symbols and common encoding artifacts (mojibake)
    let strategicText = data.strategicFindings
        .replace(/[*#]/g, '')
        .replace(/[ØÝÜÞàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ]/g, '') // Remove Latin-1 supplement garbage that appears as artifacts
        .replace(/&p/g, '\n') // Fix common PDF formatting artifacts
        .replace(/\u00A0/g, ' '); // Replace non-breaking spaces

    // Clean up bullet point artifacts looking like "9 " or "= " at start of lines
    strategicText = strategicText.replace(/^\s*[Ø=Ý9]+\s*/gm, '• ');

    // Use a slightly narrower width than the full margin width to be safe
    const safeWidth = pageWidth - (margin * 2.5);
    const strategicLines = doc.splitTextToSize(strategicText, safeWidth);
    doc.text(strategicLines, margin, currentY);

    currentY += (strategicLines.length * 4.5) + 15;

    // --- 4. CA STRATEGIC ADVICE ---
    // If logic: check if space remains, else add page
    if (currentY > 220) { doc.addPage(); currentY = 20; }
    currentY = drawSectionHeader('4. CA STRATEGIC ADVICE (RULE BASED)', currentY, [168, 85, 247]); // Purple

    // Grid for advice
    const adviceWidth = (pageWidth - (margin * 3)) / 2;
    const adviceHeight = 35; // Increased height for wrapping

    data.caAdvice.forEach((item, index) => {
        const x = index % 2 === 0 ? margin : margin + adviceWidth + margin;
        const y = currentY + (Math.floor(index / 2) * (adviceHeight + 5));

        doc.setFillColor(...colors.lightGray);
        doc.setDrawColor(200, 200, 200);
        doc.roundedRect(x, y, adviceWidth, adviceHeight, 2, 2, 'FD');

        // Type Icon placeholder
        doc.setFillColor(0, 0, 0);
        doc.circle(x + 10, y + 12, 8, 'F');
        doc.setTextColor(255, 215, 0);
        doc.setFontSize(9);
        doc.text(item.type === 'Logistics' ? 'L' : '$', x + 10, y + 15, { align: 'center' }); // Centered icon text

        // Text Wrapping
        doc.setTextColor(...colors.navy);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        const adviceLines = doc.splitTextToSize(item.advice, adviceWidth - 35); // Leave space for icon and savings
        doc.text(adviceLines, x + 22, y + 10);

        doc.setFontSize(7);
        doc.setTextColor(...colors.gray);
        doc.text(item.type.toUpperCase(), x + 22, y + 25);

        // Savings
        doc.setFontSize(10);
        doc.setTextColor(...colors.green);
        doc.setFont('helvetica', 'bold');
        doc.text(`+$${item.savings.toLocaleString()}`, x + adviceWidth - 5, y + 28, { align: 'right' });
    });

    currentY += (Math.ceil(data.caAdvice.length / 2) * (adviceHeight + 5)) + 15;

    // --- 5. PROFIT PROTECTION ---
    if (currentY > 240) { doc.addPage(); currentY = 20; }
    currentY = drawSectionHeader('5. PROFIT PROTECTION & RISK', currentY, colors.green);

    const statBoxWidth = (pageWidth - (margin * 5)) / 4;
    const statBoxHeight = 30; // Increased height for breathing room

    const drawStatBox = (index: number, title: string, value: string, color: [number, number, number]) => {
        const x = margin + (index * (statBoxWidth + margin));
        doc.setDrawColor(...color);
        doc.setFillColor(255, 255, 255);
        doc.setLineWidth(0.5);
        doc.roundedRect(x, currentY, statBoxWidth, statBoxHeight, 2, 2, 'D');

        doc.setFontSize(7);
        doc.setTextColor(...color);
        doc.setFont('helvetica', 'bold');
        const titleLines = doc.splitTextToSize(title.toUpperCase(), statBoxWidth - 4);
        doc.text(titleLines, x + (statBoxWidth / 2), currentY + 8, { align: 'center' });

        doc.setFontSize(11);
        doc.text(value, x + (statBoxWidth / 2), currentY + 22, { align: 'center' });
    };

    drawStatBox(0, 'Cash Incentive', `$${data.profitProtection.cashIncentive.toLocaleString()}`, colors.green);
    drawStatBox(1, 'Duty Drawback', `$${data.profitProtection.dutyDrawback.toLocaleString()}`, colors.blue);
    drawStatBox(2, '2026 Value at Risk', `$${data.profitProtection.revenueRisk.toLocaleString()}`, colors.red);
    drawStatBox(3, 'LDC Risk Score', `${data.profitProtection.ldcRiskScore} / 10`, [249, 115, 22]); // Orange

    if (data.profitProtection.cbamLiability > 0) {
        currentY += 35;
        doc.setFillColor(...colors.lightGray);
        doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 15, 2, 2, 'F');
        doc.setFontSize(8);
        doc.setTextColor(...colors.navy);
        doc.text(`EU CBAM Liability Warning: Estimated €${data.profitProtection.cbamLiability.toLocaleString()} carbon certificate cost.`, margin + 4, currentY + 10);
    } else {
        currentY += 35;
    }

    // --- SUM CHECK VALIDATION ---
    currentY += 10;
    if (currentY > 250) { doc.addPage(); currentY = 20; }

    doc.setFillColor(data.sumCheck.passed ? 240 : 254, data.sumCheck.passed ? 253 : 226, data.sumCheck.passed ? 244 : 226); // Light green or light red bg
    doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 12, 2, 2, 'F');

    doc.setFontSize(9);
    doc.setTextColor(data.sumCheck.passed ? 22 : 185, data.sumCheck.passed ? 101 : 28, data.sumCheck.passed ? 52 : 28);
    doc.setFont('helvetica', 'bold');
    doc.text('Sum Check Validation', margin + 4, currentY + 8);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(`Declared: $${data.sumCheck.declared} | Calculated: $${data.sumCheck.calculated} | ${data.sumCheck.passed ? 'MATCH' : 'MISMATCH'}`, pageWidth - margin - 4, currentY + 8, { align: 'right' });

    currentY += 20;

    // --- LINE ITEMS TABLE ---
    autoTable(doc, {
        startY: currentY,
        head: [['#', 'Description', 'Qty', 'Price', 'HS Code', 'LDC Impact', 'Status']],
        body: data.lineItems.map(item => [
            item.format,
            item.description,
            item.qty,
            `$${item.price}`,
            item.hsCode,
            item.ldcImpact ? '2026 Impact' : '-',
            item.status
        ]),
        theme: 'grid',
        headStyles: { fillColor: colors.navy, textColor: [255, 255, 255], fontSize: 8 },
        styles: { fontSize: 8, cellPadding: 2 },
        columnStyles: {
            0: { cellWidth: 10 },
            1: { cellWidth: 'auto' },
            2: { cellWidth: 20, halign: 'right' },
            3: { cellWidth: 20, halign: 'right' },
            4: { cellWidth: 25 },
            5: { cellWidth: 25, halign: 'center' },
            6: { cellWidth: 20 }
        }
    });

    doc.save(`CFO_Accuracy_Report_${data.invoiceNo}.pdf`);
};
